[theme]
base = "light"
primaryColor = "#7560d8"
backgroundColor = "#f3f0e8"
secondaryBackgroundColor = "#fffdf6"
textColor = "#12211b"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
fileWatcherType = "none"
